#!/usr/bin/perl

use strict;
use warnings;

my $arg = $ARGV[0];
my $offset=0;

if(scalar @ARGV == 0){
   print "output iTerm2 window/tab/panel id\n";
   print "$0 [w|t|p] [+-OFFSET]\n";
   exit(0);
}

if(defined $ARGV[1]){
   $offset = 0 + $ARGV[1];
}

my $isid = $ENV{'ITERM_SESSION_ID'};
my ($window_id,$tab_id,$panel_id) = ($isid =~ m/^w(\d+)t(\d+)p(\d+)$/);

my @out=();
foreach my $c (split '',$arg){
   if($c eq "w"){ push @out,  $window_id +$offset;}
   elsif($c eq "t"){ push @out,  $tab_id +$offset;}
   elsif($c eq "p"){ push @out, $panel_id +$offset;}
   else{ print "BAD ARGUMENT! $c"}
}

print join "\t",@out;

# printf "%d\t%d\t%d\n",$window_id,$tab_id,$panel_id;
print "\n";
